version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 3005:3005
    networks:
      - common-network 
  mysql-container:
    image: mysql
    volumes:
      - /Users/ahs/devopment/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: guang
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
